version: "3.3"

services: 
  torprivoxy:
    image: rdsubhas/tor-privoxy-alpine
    ports: 
      - 8118:9050
    networks: 
      - torprivoxyNetwork
  splash:
    image: scrapinghub/splash
    ports: 
      - 8050:8050
    # volumes: 
    #   - ./splash/proxy-profiles:/etc/splash/proxy-profiles:ro
    networks: 
      - splashNetwork
    # links: 
    #   - torprivoxy
  
  # mongo:
  #   image: mongo
  #   restart: unless-stopped
  #   container_name: mongodb
  #   # environment: 
  #   #   MONGO_INITDB_ROOT_USERNAME: root
  #   #   MONGO_INITDB_ROOT_PASSWORD: 51133940fad47d03ae61c3bbe4e5f67c7af65fda47301de532dbeed094a63c7b
  #   ports: 
  #     - 27018:27017
  #   volumes: 
  #     - mongo-database:/data/db

# volumes: 
#   mongo-database:
networks: 
  torprivoxyNetwork:
  splashNetwork: 

